### ISSUE TITLE
Line break where there shouldn't be one

### ISSUE THREAD

**Issue by SpiritAxolotl** [SpiritAxolotl/spiritaxolotl.github.io#13]
<img width="649" alt="Screen Shot 2022-04-03 at 1 33 18 PM" src="https://user-images.githubusercontent.com/83354374/161444913-765f6fc8-fa48-49dc-a241-dfd8def5a464.png">

There should not be a line break between "around" and "in".
This is on the [DEPalldialogue](https://spiritaxolotl.github.io/html/DEPalldialogue) page. 
There's also no `br` tag in the html.

**Comment by mathew27700** [comment]
try setting the font-size in the body to 0.

**Comment by FBQuail** [comment]
Disabling the "display: flex" attribute from .flex-container fixes the issue.

I looked around through the subpages, and I haven't seen any changes to how the text is contained when this attribute is off.

Do you remember what the attribute was used for?
